# The 10 data only used to build and test the tool.

data_file_list: /nfs/masi/xuk9/SPORE/clustering/pca/2020311_10_dataset/100_data_list.txt

num_processes: 20

src_root: /home/local/VANDERBILT/xuk9/03-Projects/05-ThoraxPCA
packages:
  c3d: packages/c3d/c3d
  niftyreg: packages/niftyreg/bin

reg_resample_ref_img: /nfs/masi/xuk9/SPORE/clustering/pca/2020311_10_dataset/data_preprocess_nan/00000103time20170511.nii.gz
