num_processes: 30

src_root: /nfs/masi/xuk9/singularity/thorax_combine/conda_base/src/thorax_pca
#src_root: /home/xuk9/nfs/masi/xuk9/singularity/thorax_combine/conda_base/src/thorax_pca
packages:
  c3d: packages/c3d/c3d
  niftyreg: packages/niftyreg/bin
  deedsBCV: packages/deedsBCV

